#intro
#main module


import sys
sys.path.append("C:/Users/Srikar/Desktop/withgraphics/Game")
from game_main import *
from highscores import *

def rules():
    print("\n\nThe rules of MASTERMIND are as follows.")
    print("1.You must guess the pattern generated by the computer.")
    print("2.Your pattern must be 4 characters long.")
    print("3.According to your pattern output will be give by the computer.")
    print("4.R/red will be given if input is correct and is in right place.")
    print("5.W/white will be given if input is present in generated pattern.")
    print("6.You are given only 10 tries.")
    print("6.Please enter only b for blue,g for green,r for red and y for yellow.")
    print("Enter 1. to go back or 0. to quit.")
    inp=input("Enter your choice :")
    if(inp=='1'):
        goto_module_func()
    else:
        sys.exit(0)
        #to quit command


def goto_module_func():
    print("\nEnter 1. to Play the game.")
    print("Enter 2. to read the rules.")
    print("Enter 3. to go back to introduction.")
    print("Enter 4. to check highscores.")
    print("Enter anything else to quit.")
    inp=input("Enter your choice :")
    if(inp=='1'):
        main_game()
    elif(inp=='2'):
        rules()
    elif(inp=='3'):
        main()
    elif(inp=='4'):
        hscores()
    else:
        sys.exit(0)
        #to quit  


def start_func():
    print("\n\nWelcome to MASTERMIND.")
    print("Please be ready to test your wits.")
        
    
'''def main():
    start_func()
    goto_module_func()
    
main()
'''
